//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IST.OrderSynchronizationSystem.MBAPI {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Shipment", Namespace="http://api.moldingbox.com/")]
    [System.SerializableAttribute()]
    public partial class Shipment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderIDField;
        
        private System.DateTime OrderdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        private int ShippingMethodIDField;
        
        private double CODAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Custom1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Custom2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Custom3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Custom4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Custom5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Custom6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IST.OrderSynchronizationSystem.MBAPI.Item[] ItemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderIDField, value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Orderdate {
            get {
                return this.OrderdateField;
            }
            set {
                if ((this.OrderdateField.Equals(value) != true)) {
                    this.OrderdateField = value;
                    this.RaisePropertyChanged("Orderdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Address1 {
            get {
                return this.Address1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address1Field, value) != true)) {
                    this.Address1Field = value;
                    this.RaisePropertyChanged("Address1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Address2 {
            get {
                return this.Address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address2Field, value) != true)) {
                    this.Address2Field = value;
                    this.RaisePropertyChanged("Address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Zip {
            get {
                return this.ZipField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipField, value) != true)) {
                    this.ZipField = value;
                    this.RaisePropertyChanged("Zip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public int ShippingMethodID {
            get {
                return this.ShippingMethodIDField;
            }
            set {
                if ((this.ShippingMethodIDField.Equals(value) != true)) {
                    this.ShippingMethodIDField = value;
                    this.RaisePropertyChanged("ShippingMethodID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public double CODAmount {
            get {
                return this.CODAmountField;
            }
            set {
                if ((this.CODAmountField.Equals(value) != true)) {
                    this.CODAmountField = value;
                    this.RaisePropertyChanged("CODAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string Custom1 {
            get {
                return this.Custom1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Custom1Field, value) != true)) {
                    this.Custom1Field = value;
                    this.RaisePropertyChanged("Custom1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string Custom2 {
            get {
                return this.Custom2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Custom2Field, value) != true)) {
                    this.Custom2Field = value;
                    this.RaisePropertyChanged("Custom2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string Custom3 {
            get {
                return this.Custom3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Custom3Field, value) != true)) {
                    this.Custom3Field = value;
                    this.RaisePropertyChanged("Custom3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string Custom4 {
            get {
                return this.Custom4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Custom4Field, value) != true)) {
                    this.Custom4Field = value;
                    this.RaisePropertyChanged("Custom4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string Custom5 {
            get {
                return this.Custom5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Custom5Field, value) != true)) {
                    this.Custom5Field = value;
                    this.RaisePropertyChanged("Custom5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string Custom6 {
            get {
                return this.Custom6Field;
            }
            set {
                if ((object.ReferenceEquals(this.Custom6Field, value) != true)) {
                    this.Custom6Field = value;
                    this.RaisePropertyChanged("Custom6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public IST.OrderSynchronizationSystem.MBAPI.Item[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://api.moldingbox.com/")]
    [System.SerializableAttribute()]
    public partial class Item : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SKUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        private int QuantityField;
        
        private System.Nullable<decimal> UnitPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Custom1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Custom2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Custom3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Custom4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Custom5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Custom6Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SKU {
            get {
                return this.SKUField;
            }
            set {
                if ((object.ReferenceEquals(this.SKUField, value) != true)) {
                    this.SKUField = value;
                    this.RaisePropertyChanged("SKU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<decimal> UnitPrice {
            get {
                return this.UnitPriceField;
            }
            set {
                if ((this.UnitPriceField.Equals(value) != true)) {
                    this.UnitPriceField = value;
                    this.RaisePropertyChanged("UnitPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Custom1 {
            get {
                return this.Custom1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Custom1Field, value) != true)) {
                    this.Custom1Field = value;
                    this.RaisePropertyChanged("Custom1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Custom2 {
            get {
                return this.Custom2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Custom2Field, value) != true)) {
                    this.Custom2Field = value;
                    this.RaisePropertyChanged("Custom2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Custom3 {
            get {
                return this.Custom3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Custom3Field, value) != true)) {
                    this.Custom3Field = value;
                    this.RaisePropertyChanged("Custom3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Custom4 {
            get {
                return this.Custom4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Custom4Field, value) != true)) {
                    this.Custom4Field = value;
                    this.RaisePropertyChanged("Custom4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Custom5 {
            get {
                return this.Custom5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Custom5Field, value) != true)) {
                    this.Custom5Field = value;
                    this.RaisePropertyChanged("Custom5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Custom6 {
            get {
                return this.Custom6Field;
            }
            set {
                if ((object.ReferenceEquals(this.Custom6Field, value) != true)) {
                    this.Custom6Field = value;
                    this.RaisePropertyChanged("Custom6");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://api.moldingbox.com/")]
    [System.SerializableAttribute()]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MBShipmentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IST.OrderSynchronizationSystem.MBAPI.Shipment ShipmentDataField;
        
        private bool SuccessfullyReceivedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Custom1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Custom2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Custom3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Custom4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Custom5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Custom6Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MBShipmentID {
            get {
                return this.MBShipmentIDField;
            }
            set {
                if ((this.MBShipmentIDField.Equals(value) != true)) {
                    this.MBShipmentIDField = value;
                    this.RaisePropertyChanged("MBShipmentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public IST.OrderSynchronizationSystem.MBAPI.Shipment ShipmentData {
            get {
                return this.ShipmentDataField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipmentDataField, value) != true)) {
                    this.ShipmentDataField = value;
                    this.RaisePropertyChanged("ShipmentData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool SuccessfullyReceived {
            get {
                return this.SuccessfullyReceivedField;
            }
            set {
                if ((this.SuccessfullyReceivedField.Equals(value) != true)) {
                    this.SuccessfullyReceivedField = value;
                    this.RaisePropertyChanged("SuccessfullyReceived");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Custom1 {
            get {
                return this.Custom1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Custom1Field, value) != true)) {
                    this.Custom1Field = value;
                    this.RaisePropertyChanged("Custom1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Custom2 {
            get {
                return this.Custom2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Custom2Field, value) != true)) {
                    this.Custom2Field = value;
                    this.RaisePropertyChanged("Custom2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Custom3 {
            get {
                return this.Custom3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Custom3Field, value) != true)) {
                    this.Custom3Field = value;
                    this.RaisePropertyChanged("Custom3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Custom4 {
            get {
                return this.Custom4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Custom4Field, value) != true)) {
                    this.Custom4Field = value;
                    this.RaisePropertyChanged("Custom4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Custom5 {
            get {
                return this.Custom5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Custom5Field, value) != true)) {
                    this.Custom5Field = value;
                    this.RaisePropertyChanged("Custom5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Custom6 {
            get {
                return this.Custom6Field;
            }
            set {
                if ((object.ReferenceEquals(this.Custom6Field, value) != true)) {
                    this.Custom6Field = value;
                    this.RaisePropertyChanged("Custom6");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://api.moldingbox.com/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusResponse", Namespace="http://api.moldingbox.com/")]
    [System.SerializableAttribute()]
    public partial class StatusResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MBShipmentIDField;
        
        private int ShipmentStatusIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrackingNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrackingURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LotNumberField;
        
        private bool RequestSuccessfullyReceivedField;
        
        private bool ShipmentExistsField;
        
        private bool ShipmentCanceledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Custom1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Custom2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Custom3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Custom4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Custom5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Custom6Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MBShipmentID {
            get {
                return this.MBShipmentIDField;
            }
            set {
                if ((this.MBShipmentIDField.Equals(value) != true)) {
                    this.MBShipmentIDField = value;
                    this.RaisePropertyChanged("MBShipmentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ShipmentStatusID {
            get {
                return this.ShipmentStatusIDField;
            }
            set {
                if ((this.ShipmentStatusIDField.Equals(value) != true)) {
                    this.ShipmentStatusIDField = value;
                    this.RaisePropertyChanged("ShipmentStatusID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TrackingNumber {
            get {
                return this.TrackingNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TrackingNumberField, value) != true)) {
                    this.TrackingNumberField = value;
                    this.RaisePropertyChanged("TrackingNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TrackingURL {
            get {
                return this.TrackingURLField;
            }
            set {
                if ((object.ReferenceEquals(this.TrackingURLField, value) != true)) {
                    this.TrackingURLField = value;
                    this.RaisePropertyChanged("TrackingURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string LotNumber {
            get {
                return this.LotNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.LotNumberField, value) != true)) {
                    this.LotNumberField = value;
                    this.RaisePropertyChanged("LotNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool RequestSuccessfullyReceived {
            get {
                return this.RequestSuccessfullyReceivedField;
            }
            set {
                if ((this.RequestSuccessfullyReceivedField.Equals(value) != true)) {
                    this.RequestSuccessfullyReceivedField = value;
                    this.RaisePropertyChanged("RequestSuccessfullyReceived");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool ShipmentExists {
            get {
                return this.ShipmentExistsField;
            }
            set {
                if ((this.ShipmentExistsField.Equals(value) != true)) {
                    this.ShipmentExistsField = value;
                    this.RaisePropertyChanged("ShipmentExists");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public bool ShipmentCanceled {
            get {
                return this.ShipmentCanceledField;
            }
            set {
                if ((this.ShipmentCanceledField.Equals(value) != true)) {
                    this.ShipmentCanceledField = value;
                    this.RaisePropertyChanged("ShipmentCanceled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Custom1 {
            get {
                return this.Custom1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Custom1Field, value) != true)) {
                    this.Custom1Field = value;
                    this.RaisePropertyChanged("Custom1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Custom2 {
            get {
                return this.Custom2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Custom2Field, value) != true)) {
                    this.Custom2Field = value;
                    this.RaisePropertyChanged("Custom2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Custom3 {
            get {
                return this.Custom3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Custom3Field, value) != true)) {
                    this.Custom3Field = value;
                    this.RaisePropertyChanged("Custom3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Custom4 {
            get {
                return this.Custom4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Custom4Field, value) != true)) {
                    this.Custom4Field = value;
                    this.RaisePropertyChanged("Custom4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Custom5 {
            get {
                return this.Custom5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Custom5Field, value) != true)) {
                    this.Custom5Field = value;
                    this.RaisePropertyChanged("Custom5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string Custom6 {
            get {
                return this.Custom6Field;
            }
            set {
                if ((object.ReferenceEquals(this.Custom6Field, value) != true)) {
                    this.Custom6Field = value;
                    this.RaisePropertyChanged("Custom6");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShippingMethod", Namespace="http://api.moldingbox.com/")]
    [System.SerializableAttribute()]
    public partial class ShippingMethod : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarrierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrackingURLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Carrier {
            get {
                return this.CarrierField;
            }
            set {
                if ((object.ReferenceEquals(this.CarrierField, value) != true)) {
                    this.CarrierField = value;
                    this.RaisePropertyChanged("Carrier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Method {
            get {
                return this.MethodField;
            }
            set {
                if ((object.ReferenceEquals(this.MethodField, value) != true)) {
                    this.MethodField = value;
                    this.RaisePropertyChanged("Method");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TrackingURL {
            get {
                return this.TrackingURLField;
            }
            set {
                if ((object.ReferenceEquals(this.TrackingURLField, value) != true)) {
                    this.TrackingURLField = value;
                    this.RaisePropertyChanged("TrackingURL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://api.moldingbox.com/")]
    [System.SerializableAttribute()]
    public partial class Status : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StatusName {
            get {
                return this.StatusNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusNameField, value) != true)) {
                    this.StatusNameField = value;
                    this.RaisePropertyChanged("StatusName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string StatusDescription {
            get {
                return this.StatusDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescriptionField, value) != true)) {
                    this.StatusDescriptionField = value;
                    this.RaisePropertyChanged("StatusDescription");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SingleItemResponse", Namespace="http://api.moldingbox.com/")]
    [System.SerializableAttribute()]
    public partial class SingleItemResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IST.OrderSynchronizationSystem.MBAPI.InventoryItem InventoryItemField;
        
        private bool SuccessfullyReceivedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public IST.OrderSynchronizationSystem.MBAPI.InventoryItem InventoryItem {
            get {
                return this.InventoryItemField;
            }
            set {
                if ((object.ReferenceEquals(this.InventoryItemField, value) != true)) {
                    this.InventoryItemField = value;
                    this.RaisePropertyChanged("InventoryItem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool SuccessfullyReceived {
            get {
                return this.SuccessfullyReceivedField;
            }
            set {
                if ((this.SuccessfullyReceivedField.Equals(value) != true)) {
                    this.SuccessfullyReceivedField = value;
                    this.RaisePropertyChanged("SuccessfullyReceived");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InventoryItem", Namespace="http://api.moldingbox.com/")]
    [System.SerializableAttribute()]
    public partial class InventoryItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SkuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        private int TotalQuantityOnHandField;
        
        private int TotalQuantityAllocatedField;
        
        private int TotalQuantityAvailableField;
        
        private int TotalQuantityOnOrderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Sku {
            get {
                return this.SkuField;
            }
            set {
                if ((object.ReferenceEquals(this.SkuField, value) != true)) {
                    this.SkuField = value;
                    this.RaisePropertyChanged("Sku");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int TotalQuantityOnHand {
            get {
                return this.TotalQuantityOnHandField;
            }
            set {
                if ((this.TotalQuantityOnHandField.Equals(value) != true)) {
                    this.TotalQuantityOnHandField = value;
                    this.RaisePropertyChanged("TotalQuantityOnHand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int TotalQuantityAllocated {
            get {
                return this.TotalQuantityAllocatedField;
            }
            set {
                if ((this.TotalQuantityAllocatedField.Equals(value) != true)) {
                    this.TotalQuantityAllocatedField = value;
                    this.RaisePropertyChanged("TotalQuantityAllocated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int TotalQuantityAvailable {
            get {
                return this.TotalQuantityAvailableField;
            }
            set {
                if ((this.TotalQuantityAvailableField.Equals(value) != true)) {
                    this.TotalQuantityAvailableField = value;
                    this.RaisePropertyChanged("TotalQuantityAvailable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int TotalQuantityOnOrder {
            get {
                return this.TotalQuantityOnOrderField;
            }
            set {
                if ((this.TotalQuantityOnOrderField.Equals(value) != true)) {
                    this.TotalQuantityOnOrderField = value;
                    this.RaisePropertyChanged("TotalQuantityOnOrder");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MultipleItemResponse", Namespace="http://api.moldingbox.com/")]
    [System.SerializableAttribute()]
    public partial class MultipleItemResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IST.OrderSynchronizationSystem.MBAPI.InventoryItem[] InventoryItemsField;
        
        private bool SuccessfullyReceivedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public IST.OrderSynchronizationSystem.MBAPI.InventoryItem[] InventoryItems {
            get {
                return this.InventoryItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.InventoryItemsField, value) != true)) {
                    this.InventoryItemsField = value;
                    this.RaisePropertyChanged("InventoryItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool SuccessfullyReceived {
            get {
                return this.SuccessfullyReceivedField;
            }
            set {
                if ((this.SuccessfullyReceivedField.Equals(value) != true)) {
                    this.SuccessfullyReceivedField = value;
                    this.RaisePropertyChanged("SuccessfullyReceived");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api.moldingbox.com/", ConfigurationName="MBAPI.MBAPISoap")]
    public interface MBAPISoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.moldingbox.com/Post_Shipment", ReplyAction="*")]
        IST.OrderSynchronizationSystem.MBAPI.Post_ShipmentResponse Post_Shipment(IST.OrderSynchronizationSystem.MBAPI.Post_ShipmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.moldingbox.com/Post_Shipment", ReplyAction="*")]
        System.Threading.Tasks.Task<IST.OrderSynchronizationSystem.MBAPI.Post_ShipmentResponse> Post_ShipmentAsync(IST.OrderSynchronizationSystem.MBAPI.Post_ShipmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.moldingbox.com/Retrieve_Shipment_Status", ReplyAction="*")]
        IST.OrderSynchronizationSystem.MBAPI.Retrieve_Shipment_StatusResponse Retrieve_Shipment_Status(IST.OrderSynchronizationSystem.MBAPI.Retrieve_Shipment_StatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.moldingbox.com/Retrieve_Shipment_Status", ReplyAction="*")]
        System.Threading.Tasks.Task<IST.OrderSynchronizationSystem.MBAPI.Retrieve_Shipment_StatusResponse> Retrieve_Shipment_StatusAsync(IST.OrderSynchronizationSystem.MBAPI.Retrieve_Shipment_StatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.moldingbox.com/Retrieve_Shipping_Methods", ReplyAction="*")]
        IST.OrderSynchronizationSystem.MBAPI.Retrieve_Shipping_MethodsResponse Retrieve_Shipping_Methods(IST.OrderSynchronizationSystem.MBAPI.Retrieve_Shipping_MethodsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.moldingbox.com/Retrieve_Shipping_Methods", ReplyAction="*")]
        System.Threading.Tasks.Task<IST.OrderSynchronizationSystem.MBAPI.Retrieve_Shipping_MethodsResponse> Retrieve_Shipping_MethodsAsync(IST.OrderSynchronizationSystem.MBAPI.Retrieve_Shipping_MethodsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.moldingbox.com/Retrieve_Merchant_Shipping_Methods", ReplyAction="*")]
        IST.OrderSynchronizationSystem.MBAPI.Retrieve_Merchant_Shipping_MethodsResponse Retrieve_Merchant_Shipping_Methods(IST.OrderSynchronizationSystem.MBAPI.Retrieve_Merchant_Shipping_MethodsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.moldingbox.com/Retrieve_Merchant_Shipping_Methods", ReplyAction="*")]
        System.Threading.Tasks.Task<IST.OrderSynchronizationSystem.MBAPI.Retrieve_Merchant_Shipping_MethodsResponse> Retrieve_Merchant_Shipping_MethodsAsync(IST.OrderSynchronizationSystem.MBAPI.Retrieve_Merchant_Shipping_MethodsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.moldingbox.com/Retrieve_Shipment_Status_Types", ReplyAction="*")]
        IST.OrderSynchronizationSystem.MBAPI.Retrieve_Shipment_Status_TypesResponse Retrieve_Shipment_Status_Types(IST.OrderSynchronizationSystem.MBAPI.Retrieve_Shipment_Status_TypesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.moldingbox.com/Retrieve_Shipment_Status_Types", ReplyAction="*")]
        System.Threading.Tasks.Task<IST.OrderSynchronizationSystem.MBAPI.Retrieve_Shipment_Status_TypesResponse> Retrieve_Shipment_Status_TypesAsync(IST.OrderSynchronizationSystem.MBAPI.Retrieve_Shipment_Status_TypesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.moldingbox.com/Cancel_Shipment", ReplyAction="*")]
        IST.OrderSynchronizationSystem.MBAPI.Cancel_ShipmentResponse Cancel_Shipment(IST.OrderSynchronizationSystem.MBAPI.Cancel_ShipmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.moldingbox.com/Cancel_Shipment", ReplyAction="*")]
        System.Threading.Tasks.Task<IST.OrderSynchronizationSystem.MBAPI.Cancel_ShipmentResponse> Cancel_ShipmentAsync(IST.OrderSynchronizationSystem.MBAPI.Cancel_ShipmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.moldingbox.com/Retrieve_Inventory_Item", ReplyAction="*")]
        IST.OrderSynchronizationSystem.MBAPI.Retrieve_Inventory_ItemResponse Retrieve_Inventory_Item(IST.OrderSynchronizationSystem.MBAPI.Retrieve_Inventory_ItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.moldingbox.com/Retrieve_Inventory_Item", ReplyAction="*")]
        System.Threading.Tasks.Task<IST.OrderSynchronizationSystem.MBAPI.Retrieve_Inventory_ItemResponse> Retrieve_Inventory_ItemAsync(IST.OrderSynchronizationSystem.MBAPI.Retrieve_Inventory_ItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.moldingbox.com/Retrieve_Inventory_Items", ReplyAction="*")]
        IST.OrderSynchronizationSystem.MBAPI.Retrieve_Inventory_ItemsResponse Retrieve_Inventory_Items(IST.OrderSynchronizationSystem.MBAPI.Retrieve_Inventory_ItemsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.moldingbox.com/Retrieve_Inventory_Items", ReplyAction="*")]
        System.Threading.Tasks.Task<IST.OrderSynchronizationSystem.MBAPI.Retrieve_Inventory_ItemsResponse> Retrieve_Inventory_ItemsAsync(IST.OrderSynchronizationSystem.MBAPI.Retrieve_Inventory_ItemsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Post_ShipmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Post_Shipment", Namespace="http://api.moldingbox.com/", Order=0)]
        public IST.OrderSynchronizationSystem.MBAPI.Post_ShipmentRequestBody Body;
        
        public Post_ShipmentRequest() {
        }
        
        public Post_ShipmentRequest(IST.OrderSynchronizationSystem.MBAPI.Post_ShipmentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.moldingbox.com/")]
    public partial class Post_ShipmentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ApiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public IST.OrderSynchronizationSystem.MBAPI.Shipment[] Shipments;
        
        public Post_ShipmentRequestBody() {
        }
        
        public Post_ShipmentRequestBody(string ApiKey, IST.OrderSynchronizationSystem.MBAPI.Shipment[] Shipments) {
            this.ApiKey = ApiKey;
            this.Shipments = Shipments;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Post_ShipmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Post_ShipmentResponse", Namespace="http://api.moldingbox.com/", Order=0)]
        public IST.OrderSynchronizationSystem.MBAPI.Post_ShipmentResponseBody Body;
        
        public Post_ShipmentResponse() {
        }
        
        public Post_ShipmentResponse(IST.OrderSynchronizationSystem.MBAPI.Post_ShipmentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.moldingbox.com/")]
    public partial class Post_ShipmentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public IST.OrderSynchronizationSystem.MBAPI.Response[] Post_ShipmentResult;
        
        public Post_ShipmentResponseBody() {
        }
        
        public Post_ShipmentResponseBody(IST.OrderSynchronizationSystem.MBAPI.Response[] Post_ShipmentResult) {
            this.Post_ShipmentResult = Post_ShipmentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Retrieve_Shipment_StatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Retrieve_Shipment_Status", Namespace="http://api.moldingbox.com/", Order=0)]
        public IST.OrderSynchronizationSystem.MBAPI.Retrieve_Shipment_StatusRequestBody Body;
        
        public Retrieve_Shipment_StatusRequest() {
        }
        
        public Retrieve_Shipment_StatusRequest(IST.OrderSynchronizationSystem.MBAPI.Retrieve_Shipment_StatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.moldingbox.com/")]
    public partial class Retrieve_Shipment_StatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ApiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public IST.OrderSynchronizationSystem.MBAPI.ArrayOfInt MBShipmentIDs;
        
        public Retrieve_Shipment_StatusRequestBody() {
        }
        
        public Retrieve_Shipment_StatusRequestBody(string ApiKey, IST.OrderSynchronizationSystem.MBAPI.ArrayOfInt MBShipmentIDs) {
            this.ApiKey = ApiKey;
            this.MBShipmentIDs = MBShipmentIDs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Retrieve_Shipment_StatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Retrieve_Shipment_StatusResponse", Namespace="http://api.moldingbox.com/", Order=0)]
        public IST.OrderSynchronizationSystem.MBAPI.Retrieve_Shipment_StatusResponseBody Body;
        
        public Retrieve_Shipment_StatusResponse() {
        }
        
        public Retrieve_Shipment_StatusResponse(IST.OrderSynchronizationSystem.MBAPI.Retrieve_Shipment_StatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.moldingbox.com/")]
    public partial class Retrieve_Shipment_StatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public IST.OrderSynchronizationSystem.MBAPI.StatusResponse[] Retrieve_Shipment_StatusResult;
        
        public Retrieve_Shipment_StatusResponseBody() {
        }
        
        public Retrieve_Shipment_StatusResponseBody(IST.OrderSynchronizationSystem.MBAPI.StatusResponse[] Retrieve_Shipment_StatusResult) {
            this.Retrieve_Shipment_StatusResult = Retrieve_Shipment_StatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Retrieve_Shipping_MethodsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Retrieve_Shipping_Methods", Namespace="http://api.moldingbox.com/", Order=0)]
        public IST.OrderSynchronizationSystem.MBAPI.Retrieve_Shipping_MethodsRequestBody Body;
        
        public Retrieve_Shipping_MethodsRequest() {
        }
        
        public Retrieve_Shipping_MethodsRequest(IST.OrderSynchronizationSystem.MBAPI.Retrieve_Shipping_MethodsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Retrieve_Shipping_MethodsRequestBody {
        
        public Retrieve_Shipping_MethodsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Retrieve_Shipping_MethodsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Retrieve_Shipping_MethodsResponse", Namespace="http://api.moldingbox.com/", Order=0)]
        public IST.OrderSynchronizationSystem.MBAPI.Retrieve_Shipping_MethodsResponseBody Body;
        
        public Retrieve_Shipping_MethodsResponse() {
        }
        
        public Retrieve_Shipping_MethodsResponse(IST.OrderSynchronizationSystem.MBAPI.Retrieve_Shipping_MethodsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.moldingbox.com/")]
    public partial class Retrieve_Shipping_MethodsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public IST.OrderSynchronizationSystem.MBAPI.ShippingMethod[] Retrieve_Shipping_MethodsResult;
        
        public Retrieve_Shipping_MethodsResponseBody() {
        }
        
        public Retrieve_Shipping_MethodsResponseBody(IST.OrderSynchronizationSystem.MBAPI.ShippingMethod[] Retrieve_Shipping_MethodsResult) {
            this.Retrieve_Shipping_MethodsResult = Retrieve_Shipping_MethodsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Retrieve_Merchant_Shipping_MethodsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Retrieve_Merchant_Shipping_Methods", Namespace="http://api.moldingbox.com/", Order=0)]
        public IST.OrderSynchronizationSystem.MBAPI.Retrieve_Merchant_Shipping_MethodsRequestBody Body;
        
        public Retrieve_Merchant_Shipping_MethodsRequest() {
        }
        
        public Retrieve_Merchant_Shipping_MethodsRequest(IST.OrderSynchronizationSystem.MBAPI.Retrieve_Merchant_Shipping_MethodsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.moldingbox.com/")]
    public partial class Retrieve_Merchant_Shipping_MethodsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ApiKey;
        
        public Retrieve_Merchant_Shipping_MethodsRequestBody() {
        }
        
        public Retrieve_Merchant_Shipping_MethodsRequestBody(string ApiKey) {
            this.ApiKey = ApiKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Retrieve_Merchant_Shipping_MethodsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Retrieve_Merchant_Shipping_MethodsResponse", Namespace="http://api.moldingbox.com/", Order=0)]
        public IST.OrderSynchronizationSystem.MBAPI.Retrieve_Merchant_Shipping_MethodsResponseBody Body;
        
        public Retrieve_Merchant_Shipping_MethodsResponse() {
        }
        
        public Retrieve_Merchant_Shipping_MethodsResponse(IST.OrderSynchronizationSystem.MBAPI.Retrieve_Merchant_Shipping_MethodsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.moldingbox.com/")]
    public partial class Retrieve_Merchant_Shipping_MethodsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public IST.OrderSynchronizationSystem.MBAPI.ShippingMethod[] Retrieve_Merchant_Shipping_MethodsResult;
        
        public Retrieve_Merchant_Shipping_MethodsResponseBody() {
        }
        
        public Retrieve_Merchant_Shipping_MethodsResponseBody(IST.OrderSynchronizationSystem.MBAPI.ShippingMethod[] Retrieve_Merchant_Shipping_MethodsResult) {
            this.Retrieve_Merchant_Shipping_MethodsResult = Retrieve_Merchant_Shipping_MethodsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Retrieve_Shipment_Status_TypesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Retrieve_Shipment_Status_Types", Namespace="http://api.moldingbox.com/", Order=0)]
        public IST.OrderSynchronizationSystem.MBAPI.Retrieve_Shipment_Status_TypesRequestBody Body;
        
        public Retrieve_Shipment_Status_TypesRequest() {
        }
        
        public Retrieve_Shipment_Status_TypesRequest(IST.OrderSynchronizationSystem.MBAPI.Retrieve_Shipment_Status_TypesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Retrieve_Shipment_Status_TypesRequestBody {
        
        public Retrieve_Shipment_Status_TypesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Retrieve_Shipment_Status_TypesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Retrieve_Shipment_Status_TypesResponse", Namespace="http://api.moldingbox.com/", Order=0)]
        public IST.OrderSynchronizationSystem.MBAPI.Retrieve_Shipment_Status_TypesResponseBody Body;
        
        public Retrieve_Shipment_Status_TypesResponse() {
        }
        
        public Retrieve_Shipment_Status_TypesResponse(IST.OrderSynchronizationSystem.MBAPI.Retrieve_Shipment_Status_TypesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.moldingbox.com/")]
    public partial class Retrieve_Shipment_Status_TypesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public IST.OrderSynchronizationSystem.MBAPI.Status[] Retrieve_Shipment_Status_TypesResult;
        
        public Retrieve_Shipment_Status_TypesResponseBody() {
        }
        
        public Retrieve_Shipment_Status_TypesResponseBody(IST.OrderSynchronizationSystem.MBAPI.Status[] Retrieve_Shipment_Status_TypesResult) {
            this.Retrieve_Shipment_Status_TypesResult = Retrieve_Shipment_Status_TypesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Cancel_ShipmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Cancel_Shipment", Namespace="http://api.moldingbox.com/", Order=0)]
        public IST.OrderSynchronizationSystem.MBAPI.Cancel_ShipmentRequestBody Body;
        
        public Cancel_ShipmentRequest() {
        }
        
        public Cancel_ShipmentRequest(IST.OrderSynchronizationSystem.MBAPI.Cancel_ShipmentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.moldingbox.com/")]
    public partial class Cancel_ShipmentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ApiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public IST.OrderSynchronizationSystem.MBAPI.ArrayOfInt MBShipmentIDs;
        
        public Cancel_ShipmentRequestBody() {
        }
        
        public Cancel_ShipmentRequestBody(string ApiKey, IST.OrderSynchronizationSystem.MBAPI.ArrayOfInt MBShipmentIDs) {
            this.ApiKey = ApiKey;
            this.MBShipmentIDs = MBShipmentIDs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Cancel_ShipmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Cancel_ShipmentResponse", Namespace="http://api.moldingbox.com/", Order=0)]
        public IST.OrderSynchronizationSystem.MBAPI.Cancel_ShipmentResponseBody Body;
        
        public Cancel_ShipmentResponse() {
        }
        
        public Cancel_ShipmentResponse(IST.OrderSynchronizationSystem.MBAPI.Cancel_ShipmentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.moldingbox.com/")]
    public partial class Cancel_ShipmentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public IST.OrderSynchronizationSystem.MBAPI.StatusResponse[] Cancel_ShipmentResult;
        
        public Cancel_ShipmentResponseBody() {
        }
        
        public Cancel_ShipmentResponseBody(IST.OrderSynchronizationSystem.MBAPI.StatusResponse[] Cancel_ShipmentResult) {
            this.Cancel_ShipmentResult = Cancel_ShipmentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Retrieve_Inventory_ItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Retrieve_Inventory_Item", Namespace="http://api.moldingbox.com/", Order=0)]
        public IST.OrderSynchronizationSystem.MBAPI.Retrieve_Inventory_ItemRequestBody Body;
        
        public Retrieve_Inventory_ItemRequest() {
        }
        
        public Retrieve_Inventory_ItemRequest(IST.OrderSynchronizationSystem.MBAPI.Retrieve_Inventory_ItemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.moldingbox.com/")]
    public partial class Retrieve_Inventory_ItemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ApiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SKU;
        
        public Retrieve_Inventory_ItemRequestBody() {
        }
        
        public Retrieve_Inventory_ItemRequestBody(string ApiKey, string SKU) {
            this.ApiKey = ApiKey;
            this.SKU = SKU;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Retrieve_Inventory_ItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Retrieve_Inventory_ItemResponse", Namespace="http://api.moldingbox.com/", Order=0)]
        public IST.OrderSynchronizationSystem.MBAPI.Retrieve_Inventory_ItemResponseBody Body;
        
        public Retrieve_Inventory_ItemResponse() {
        }
        
        public Retrieve_Inventory_ItemResponse(IST.OrderSynchronizationSystem.MBAPI.Retrieve_Inventory_ItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.moldingbox.com/")]
    public partial class Retrieve_Inventory_ItemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public IST.OrderSynchronizationSystem.MBAPI.SingleItemResponse Retrieve_Inventory_ItemResult;
        
        public Retrieve_Inventory_ItemResponseBody() {
        }
        
        public Retrieve_Inventory_ItemResponseBody(IST.OrderSynchronizationSystem.MBAPI.SingleItemResponse Retrieve_Inventory_ItemResult) {
            this.Retrieve_Inventory_ItemResult = Retrieve_Inventory_ItemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Retrieve_Inventory_ItemsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Retrieve_Inventory_Items", Namespace="http://api.moldingbox.com/", Order=0)]
        public IST.OrderSynchronizationSystem.MBAPI.Retrieve_Inventory_ItemsRequestBody Body;
        
        public Retrieve_Inventory_ItemsRequest() {
        }
        
        public Retrieve_Inventory_ItemsRequest(IST.OrderSynchronizationSystem.MBAPI.Retrieve_Inventory_ItemsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.moldingbox.com/")]
    public partial class Retrieve_Inventory_ItemsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ApiKey;
        
        public Retrieve_Inventory_ItemsRequestBody() {
        }
        
        public Retrieve_Inventory_ItemsRequestBody(string ApiKey) {
            this.ApiKey = ApiKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Retrieve_Inventory_ItemsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Retrieve_Inventory_ItemsResponse", Namespace="http://api.moldingbox.com/", Order=0)]
        public IST.OrderSynchronizationSystem.MBAPI.Retrieve_Inventory_ItemsResponseBody Body;
        
        public Retrieve_Inventory_ItemsResponse() {
        }
        
        public Retrieve_Inventory_ItemsResponse(IST.OrderSynchronizationSystem.MBAPI.Retrieve_Inventory_ItemsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.moldingbox.com/")]
    public partial class Retrieve_Inventory_ItemsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public IST.OrderSynchronizationSystem.MBAPI.MultipleItemResponse Retrieve_Inventory_ItemsResult;
        
        public Retrieve_Inventory_ItemsResponseBody() {
        }
        
        public Retrieve_Inventory_ItemsResponseBody(IST.OrderSynchronizationSystem.MBAPI.MultipleItemResponse Retrieve_Inventory_ItemsResult) {
            this.Retrieve_Inventory_ItemsResult = Retrieve_Inventory_ItemsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MBAPISoapChannel : IST.OrderSynchronizationSystem.MBAPI.MBAPISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MBAPISoapClient : System.ServiceModel.ClientBase<IST.OrderSynchronizationSystem.MBAPI.MBAPISoap>, IST.OrderSynchronizationSystem.MBAPI.MBAPISoap {
        
        public MBAPISoapClient() {
        }
        
        public MBAPISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MBAPISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MBAPISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MBAPISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public IST.OrderSynchronizationSystem.MBAPI.Post_ShipmentResponse Post_Shipment(IST.OrderSynchronizationSystem.MBAPI.Post_ShipmentRequest request) {
            return base.Channel.Post_Shipment(request);
        }
        
        public System.Threading.Tasks.Task<IST.OrderSynchronizationSystem.MBAPI.Post_ShipmentResponse> Post_ShipmentAsync(IST.OrderSynchronizationSystem.MBAPI.Post_ShipmentRequest request) {
            return base.Channel.Post_ShipmentAsync(request);
        }
        
        public IST.OrderSynchronizationSystem.MBAPI.Retrieve_Shipment_StatusResponse Retrieve_Shipment_Status(IST.OrderSynchronizationSystem.MBAPI.Retrieve_Shipment_StatusRequest request) {
            return base.Channel.Retrieve_Shipment_Status(request);
        }
        
        public System.Threading.Tasks.Task<IST.OrderSynchronizationSystem.MBAPI.Retrieve_Shipment_StatusResponse> Retrieve_Shipment_StatusAsync(IST.OrderSynchronizationSystem.MBAPI.Retrieve_Shipment_StatusRequest request) {
            return base.Channel.Retrieve_Shipment_StatusAsync(request);
        }
        
        public IST.OrderSynchronizationSystem.MBAPI.Retrieve_Shipping_MethodsResponse Retrieve_Shipping_Methods(IST.OrderSynchronizationSystem.MBAPI.Retrieve_Shipping_MethodsRequest request) {
            return base.Channel.Retrieve_Shipping_Methods(request);
        }
        
        public System.Threading.Tasks.Task<IST.OrderSynchronizationSystem.MBAPI.Retrieve_Shipping_MethodsResponse> Retrieve_Shipping_MethodsAsync(IST.OrderSynchronizationSystem.MBAPI.Retrieve_Shipping_MethodsRequest request) {
            return base.Channel.Retrieve_Shipping_MethodsAsync(request);
        }
        
        public IST.OrderSynchronizationSystem.MBAPI.Retrieve_Merchant_Shipping_MethodsResponse Retrieve_Merchant_Shipping_Methods(IST.OrderSynchronizationSystem.MBAPI.Retrieve_Merchant_Shipping_MethodsRequest request) {
            return base.Channel.Retrieve_Merchant_Shipping_Methods(request);
        }
        
        public System.Threading.Tasks.Task<IST.OrderSynchronizationSystem.MBAPI.Retrieve_Merchant_Shipping_MethodsResponse> Retrieve_Merchant_Shipping_MethodsAsync(IST.OrderSynchronizationSystem.MBAPI.Retrieve_Merchant_Shipping_MethodsRequest request) {
            return base.Channel.Retrieve_Merchant_Shipping_MethodsAsync(request);
        }
        
        public IST.OrderSynchronizationSystem.MBAPI.Retrieve_Shipment_Status_TypesResponse Retrieve_Shipment_Status_Types(IST.OrderSynchronizationSystem.MBAPI.Retrieve_Shipment_Status_TypesRequest request) {
            return base.Channel.Retrieve_Shipment_Status_Types(request);
        }
        
        public System.Threading.Tasks.Task<IST.OrderSynchronizationSystem.MBAPI.Retrieve_Shipment_Status_TypesResponse> Retrieve_Shipment_Status_TypesAsync(IST.OrderSynchronizationSystem.MBAPI.Retrieve_Shipment_Status_TypesRequest request) {
            return base.Channel.Retrieve_Shipment_Status_TypesAsync(request);
        }
        
        public IST.OrderSynchronizationSystem.MBAPI.Cancel_ShipmentResponse Cancel_Shipment(IST.OrderSynchronizationSystem.MBAPI.Cancel_ShipmentRequest request) {
            return base.Channel.Cancel_Shipment(request);
        }
        
        public System.Threading.Tasks.Task<IST.OrderSynchronizationSystem.MBAPI.Cancel_ShipmentResponse> Cancel_ShipmentAsync(IST.OrderSynchronizationSystem.MBAPI.Cancel_ShipmentRequest request) {
            return base.Channel.Cancel_ShipmentAsync(request);
        }
        
        public IST.OrderSynchronizationSystem.MBAPI.Retrieve_Inventory_ItemResponse Retrieve_Inventory_Item(IST.OrderSynchronizationSystem.MBAPI.Retrieve_Inventory_ItemRequest request) {
            return base.Channel.Retrieve_Inventory_Item(request);
        }
        
        public System.Threading.Tasks.Task<IST.OrderSynchronizationSystem.MBAPI.Retrieve_Inventory_ItemResponse> Retrieve_Inventory_ItemAsync(IST.OrderSynchronizationSystem.MBAPI.Retrieve_Inventory_ItemRequest request) {
            return base.Channel.Retrieve_Inventory_ItemAsync(request);
        }
        
        public IST.OrderSynchronizationSystem.MBAPI.Retrieve_Inventory_ItemsResponse Retrieve_Inventory_Items(IST.OrderSynchronizationSystem.MBAPI.Retrieve_Inventory_ItemsRequest request) {
            return base.Channel.Retrieve_Inventory_Items(request);
        }
        
        public System.Threading.Tasks.Task<IST.OrderSynchronizationSystem.MBAPI.Retrieve_Inventory_ItemsResponse> Retrieve_Inventory_ItemsAsync(IST.OrderSynchronizationSystem.MBAPI.Retrieve_Inventory_ItemsRequest request) {
            return base.Channel.Retrieve_Inventory_ItemsAsync(request);
        }
    }
}
