//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IST.OrderSynchronizationSystem {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CreateDBScript {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateDBScript() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IST.OrderSynchronizationSystem.CreateDBScript", typeof(CreateDBScript).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///CREATE TABLE [dbo].[Logs](
        ///	[LogId] [bigint] IDENTITY(1,1) NOT NULL,
        ///	[LogTypeId] [int] NOT NULL,
        ///	[OrderId] [bigint] NULL,
        ///	[LogText] [nvarchar](max) NOT NULL,
        ///	[CreatedOn] [datetime] NOT NULL,
        /// CONSTRAINT [PK_Log] PRIMARY KEY CLUSTERED 
        ///(
        ///	[LogId] ASC
        ///)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
        ///) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
        ///
        ///
        ///CREATE TABLE [dbo].[LogTypes](
        ///	[LogTypeId] [int] IDENTITY(1,1) NO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateDbScript {
            get {
                return ResourceManager.GetString("CreateDbScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      create PROCEDURE [dbo].[USPCreateOSSOrders]
        ///      @createOssOrders dbo.CreateOSSOrdersTableType READONLY
        ///      As
        ///      Begin
        ///      -- SET NOCOUNT ON added to prevent extra result sets from
        ///      -- interfering with SELECT statements.
        ///      Set NoCount On;
        ///
        ///      Insert Into [OSSOrders]
        ///      ([THubOrderId]
        ///      ,[THubOrderReferenceNo]
        ///      ,[CreatedOn]
        ///      ,[THubCompleteOrder]
        ///      ,[OrderStatus])
        ///      SELECT [THubOrderId]
        ///      ,[THubOrderReferenceNo]
        ///      ,[CreatedOn]
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateOssOrders {
            get {
                return ResourceManager.GetString("CreateOssOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      CREATE PROCEDURE [dbo].[USPLoadOrdersFromStaging]
        ///      @OrderStatus int
        ///      AS
        ///      BEGIN
        ///      -- SET NOCOUNT ON added to prevent extra result sets from
        ///      -- interfering with SELECT statements.
        ///      SET NOCOUNT ON;
        ///
        ///      SELECT [OSSOrderId]
        ///      ,[THubOrderId]
        ///      ,[THubOrderReferenceNo]
        ///      ,[CreatedOn]
        ///      ,[THubCompleteOrder]
        ///      ,[SentToMB]
        ///      ,[SentToMBOn]
        ///      ,[MBPostShipmentMessage]
        ///      ,[MBPostShipmentResponseMessage]
        ///      ,[MBSuccessfullyReceived [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateUSP_LoadOrdersFromStaging {
            get {
                return ResourceManager.GetString("CreateUSP_LoadOrdersFromStaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      CREATE PROCEDURE [dbo].[USPUpdateOrderAfterMoldingBoxShipmentRequest]
        ///      -- Add the parameters for the stored procedure here
        ///      @OSSOrderId bigint,
        ///      @SentToMB bit,
        ///      @SentToMBOn datetime,
        ///      @MBPostShipmentMessage nvarchar(MAX),
        ///      @MBPostShipmentResponseMessage nvarchar(MAX),
        ///      @MBSuccessfullyReceived bit,
        ///      @MBShipmentId nvarchar(15),
        ///      @MBShipmentSubmitError nvarchar(MAX),
        ///      @OrderStatus int,
        ///      @CancelMessage nvarchar(MAX),
        ///      @MBShipmentMet [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateUSP_UpdateOrderAfterMoldingBoxShipmentRequest {
            get {
                return ResourceManager.GetString("CreateUSP_UpdateOrderAfterMoldingBoxShipmentRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    INSERT INTO [dbo].[LogTypes]
        ///           ([LogType]
        ///           ,[CreatedOn])
        ///     VALUES
        ///           (&apos;Info&apos;, @CreatedOn)    
        ///  .
        /// </summary>
        internal static string InsertLogType {
            get {
                return ResourceManager.GetString("InsertLogType", resourceCulture);
            }
        }
    }
}
