//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IST.OrderSynchronizationSystem {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IST.OrderSynchronizationSystem.SqlResource", typeof(SqlResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select count(*) from Orders.
        /// </summary>
        internal static string source_sql_verify {
            get {
                return ResourceManager.GetString("source_sql_verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select LastOrderExecutionTime from LastOrderExecutionDetails.
        /// </summary>
        internal static string staging_sql_LastExecutionTimeQuery {
            get {
                return ResourceManager.GetString("staging_sql_LastExecutionTimeQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select ord.OrderId As OrderID, 
        ///  ord.OrderDate As Orderdate, 
        ///  SAddr_Company As Company,
        ///  SAddr_FirstName As FirstName,
        ///  SAddr_LastName As LastName,
        ///  SAddr_Line1 As Address1,
        ///  SAddr_Line2 As Address2,
        ///  SAddr_City As City,
        ///  SAddr_State As &apos;State&apos;,
        ///  SAddr_Country As Country,
        ///  SAddr_Email1 As Email,
        ///  SAddr_Phone1 As Phone,
        ///  WebShipMethod As ShippingMethodID,
        ///  CustomValue1 as Custom1,
        ///  CustomValue2 as Custom2,
        ///  CustomValue3 as Custom3,
        ///  CustomValue4 as Custom4,
        ///  CustomValue5 as [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string staging_sql_PullOrdersFromThubQuery {
            get {
                return ResourceManager.GetString("staging_sql_PullOrdersFromThubQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select count(*) from OSSOrders.
        /// </summary>
        internal static string staging_sql_verify {
            get {
                return ResourceManager.GetString("staging_sql_verify", resourceCulture);
            }
        }
    }
}
